apiVersion: v1
kind: Pod
metadata:
  name: secret-nginx
  namespace: dev

spec:
  volumes:
    - name: nginx-secret
      secret:
        secretName: nginx-secret

  containers:
    - name: secret-nginx
      image: nginx:1.17.1
      volumeMounts:
        - name: nginx-secret
          mountPath: /secret/config
