version: "3"

services:
  web:
    container_name: 'nginx01' # 相当于docker run --name nginx01
    ports: # 为了暴露端口在主机上访问
    	- "80:80" # 相当于docker run -p 80:80
    volumes: # 为了让容器内的数据持久化
      - nginx:/etc/nginx # 相当于docker run -v nginx:/etc/nginx
    networks: # 为了让整个项目的容器工作在一个自定义的网络中
    	- web # 相当于docker run --net web 
    build: # 在启动服务时用来将指定的dockerfile脚本进行执行构建出对应的镜像，然后使用该镜像
      context: '.' # 指定dockerfile所在的目录，路径计算时相对于docker-compose.yml所在的目录进行计算
      dockerfile: 'dokerfile'
    depends_on: # 代表着这个服务依赖于哪些服务，要等到那些服务所属的容器启动后，这个服务所属的容器才启动(不过不是说等到彻底启动后，这个才会启动，而是依赖服务启动到一定程度了，这个就可以启动了)
      - mysql  # 说明web服务必须等到mysql服务启动后，才能启动！这里写的是服务名，而不是container_name容器名！

  mysql:
    container_name: 'mysql01'
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    enviroment: # 定义环境变量
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:5.7.32


volumes:
  nginx: # 相当于docker volume create nginx（定义上边服务用到的数据卷名称）
  mysql:
  # 意思是使用外部自定义创建的volume，即自己手动创建一个volume，名字叫做mysql。如果不这么做，比如上边的nginx的volume
  # 如果是nginx那种创建volume的方式，那么实际上生成的volume的名字是项目+volume名，即项目名_nginx
    external: true 
networks:
  web: # 相当于docker network create web（定义上边服务用到的网桥名称）