apiVersion: v1
kind: Pod
metadata:
  name: volume-pod1
  namespace: dev
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc1
        readOnly: false
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        ['/bin/sh', '-c', 'while true;do echo pod1 >> /root/out.txt; sleep 10; done;']
      volumeMounts:
        - name: volume
          mountPath: /root/
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-pod2
  namespace: dev
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc2
        readOnly: false
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        ['/bin/sh', '-c', 'while true;do echo pod2 >> /root/out.txt; sleep 10; done;']
      volumeMounts:
        - name: volume
          mountPath: /root/

---
apiVersion: v1
kind: Pod
metadata:
  name: volume-pod3
  namespace: dev
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc3
        readOnly: false
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        ['/bin/sh', '-c', 'while true;do echo pod2 >> /root/out.txt; sleep 10; done;']
      volumeMounts:
        - name: volume
          mountPath: /root/
